#!/bin/sh
#
# init.d startup/shutdown script for Tangelo.
#
# This was written to conform to the deployment practices of the XDATA summer
# camp Vis VM.  It works by deferring to the 'tangelo' script, but placing the
# log and PID files in /var.

here=`dirname $0`
logdir=/var/log
piddir=/var/run

retval=0

case "$1" in
    start)
        ${here}/tangelo --logdir ${logdir} --piddir ${piddir} start
        retval=$?
        ;;

    stop)
        ${here}/tangelo --logdir ${logdir} --piddir ${piddir} stop
        retval=$?
        ;;

    restart)
        ${here}/tangelo --logdir ${logdir} --piddir ${piddir} restart
        retval=$?
        ;;

    *)
        echo "usage: $0 {start|stop|restart}" >/dev/stderr
        exit 1
esac

exit ${RETVAL}
