/*jslint browser: true */
/*globals declareTest, compareImages, toImageData, Promise, d3 */

declareTest({
    name: "Numbers generated by Primes demo should be prime",
    url: "/examples/primes",
    test: function (page) {
        "use strict";

        var smallPrime = function (n) {
            var smallPrimes = [2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31];
            return smallPrimes.indexOf(n) !== -1;
        };

        return new Promise(function (deliver) {
            var nums;

            window.setTimeout(function () {
                nums = page.evaluate(function () {
                    var primes = [];

                    d3.selectAll("div#primes > div.card")
                        .each(function () {
                            primes.push(d3.select(this).text());
                        });

                    return primes.map(JSON.parse);
                });

                console.log("expected: five prime numbers");
                console.log("received: " + nums);

                deliver(nums.map(smallPrime)
                    .reduce(function (x, y) {
                        return x && y;
                    }, true));
            }, 7000);
        });
    }
});
