/*jslint browser: true */
/*globals declareTest, d3 */

declareTest({
    name: "Numbers generated by Primes demo should be prime",
    url: "/examples/primes",
    delay: 7000,
    test: function () {
        "use strict";

        var smallPrime = function (n) {
            var smallPrimes = [2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31];
            return smallPrimes.indexOf(n) !== -1;
        },
            primes = [];

        d3.selectAll("div#primes > div.card")
            .each(function () {
                primes.push(d3.select(this).text());
            });

        return primes.map(JSON.parse)
            .map(smallPrime)
            .reduce(function (x, y) {
                return x && y;
            }, true);
    }
});
