#!/bin/sh
#
# init.d startup/shutdown script for Tangelo.
#
# This was written to conform to the deployment practices of the XDATA summer
# camp Vis VM.
retval=0

case "$1" in
    start)
        ${tangelo} start
        retval=$?
        ;;

    stop)
        ${tangelo} stop
        retval=$?
        ;;

    restart)
        ${tangelo} restart
        retval=$?
        ;;

    *)
        echo "usage: $0 {start|stop|restart}" >/dev/stderr
        exit 1
esac

exit ${RETVAL}
